---

- name: Tune sysctl
  ansible.posix.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: "{{ item.state }}"
    sysctl_set: true
  loop: "{{ sysctl_antiddos }}"
  loop_control:
    label: "{{ item.name }}"
  notify: Reload sysctl
