---
name: CI
'on':
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: '0 6 * * 1'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    working-directory: 'jtprogru.sysctl'

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v7
        with:
          path: 'jtprogru.sysctl'

      - name: Set up Python 3.
        uses: actions/setup-python@v7
        with:
          python-version: '3.x'

      - name: Install test dependencies.
        run: pip3 install --upgrade pip

      - name: Install test dependencies.
        run: pip3 install yamllint ansible-lint

      - name: Install collection dependencies.
        run: ansible-galaxy collection install -r requirements.yml

      - name: Lint code.
        run: |
          yamllint .
          ansible-lint

  molecule:
    name: Molecule
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        distro:
          - ubuntu2204
          - ubuntu2404
          - debian11
          - debian12

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v7
        with:
          path: 'jtprogru.sysctl'

      - name: Set up Python 3.
        uses: actions/setup-python@v7
        with:
          python-version: '3.x'

      - name: Install test dependencies.
        run: pip3 install --upgrade pip

      - name: Install test dependencies.
        run: pip3 install ansible-core molecule 'molecule-plugins[docker]' docker

      - name: Install collection dependencies.
        run: |
          ansible-galaxy collection install -r requirements.yml
          ansible-galaxy collection install community.docker

      - name: Run Molecule tests.
        run: molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}
